# Generated by Django 4.0.4 on 2022-06-08 11:58

from django.conf import settings
from django.db import migrations, models
import scipy.signal.wavelets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=scipy.signal.wavelets.cascade, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
