# Generated by Django 4.0.4 on 2022-06-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(height_field=321, upload_to='', width_field=308)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
